---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-tools
  labels:
    app: youtube-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-tools
  template:
    metadata:
      labels:
        app: youtube-tools
    spec:
      containers:
        - name: youtube-tools
          image: youtube-tools:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: CONFIG_PATH
              value: "/app/conf/config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /app/conf
            - name: data-volume
              mountPath: /data/yt
          livenessProbe:
            httpGet:
              path: /api/yt/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/yt/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: youtube-tools-pvc
        - name: config-volume
          configMap:
            name: youtube-tools-conf

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: youtube-tools-conf
data:
  config.yaml: |
    # 服务器配置
    server:
      port: 8080

    # 日志配置
    log:
      level: info    # debug, info, warn, error
      format: json   # json, console

    # yt-dlp 配置
    ytdlp:
      path: /usr/bin/yt-dlp
      ffmpeg_path: /usr/bin/ffmpeg
      download_dir: /data/yt
      cookies_path: /data/yt/cookies.txt
      proxy: ""
    # 环境配置
    env: production

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtube-tools-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - prefix=public/ytb/
    - allow-delete
    - allow-overwrite
    - file-mode=0666
    - dir-mode=0777
  csi:
    driver: s3.csi.aws.com
    volumeHandle: chev-s3-youtube-tools-handler
    volumeAttributes:
      bucketName: chev-resources
      region: us-east-2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-tools-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: youtube-tools-pv

---
kind: Service
apiVersion: v1
metadata:
  name: youtube-tools-svc
spec:
  selector:
    app: youtube-tools
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: api