basePath: /api/v1
definitions:
  handlers.StartDownloadRequest:
    properties:
      filename:
        type: string
      format:
        type: string
      output_dir:
        type: string
      url:
        type: string
    required:
    - url
    type: object
  response.Response:
    properties:
      code:
        type: string
      data: {}
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: A RESTful API service for YouTube video operations using yt-dlp
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: YouTube Tools API
  version: "1.0"
paths:
  /download:
    post:
      consumes:
      - application/json
      description: 开始下载指定 URL 的视频
      parameters:
      - description: 下载请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.StartDownloadRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 开始下载视频
      tags:
      - 下载
  /download/{task_id}:
    delete:
      description: 取消指定任务 ID 的下载
      parameters:
      - description: 任务 ID
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: 取消下载
      tags:
      - 下载
  /health:
    get:
      description: 获取 API 服务的健康状态
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 健康检查
      tags:
      - 系统
  /info:
    get:
      description: 获取指定 URL 的视频信息
      parameters:
      - description: 视频 URL
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取视频信息
      tags:
      - 视频
  /status/{task_id}:
    get:
      description: 获取指定任务 ID 的下载状态
      parameters:
      - description: 任务 ID
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取下载状态
      tags:
      - 下载
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
